// background.js — TurboDownloader Extension Service Worker
// Security model: extension always talks to 127.0.0.1:9988 (local TD only).
// Authentication is handled via a local token generated by TD at startup.
// No credentials or host config needed.

// ── Constants ─────────────────────────────────────────────────────────────────

const TD_HOST        = "http://127.0.0.1:9988";
const TOKEN_MARGIN_MS = 5 * 60 * 1000;  // renew 5 min before expiry

// ── Default settings ──────────────────────────────────────────────────────────

const DEFAULT_SETTINGS = {
  token:       null,
  tokenExpiry: 0,
  intercept:   false,
  extensions:  [".mkv", ".mp4", ".avi", ".mov", ".wmv", ".mp3", ".flac",
                ".zip", ".rar", ".7z", ".iso", ".exe", ".msi"],
  dest:        "",
};

// ── Storage helpers ───────────────────────────────────────────────────────────

async function getSettings() {
  const stored = await chrome.storage.local.get(DEFAULT_SETTINGS);
  return { ...DEFAULT_SETTINGS, ...stored };
}

async function saveSettings(patch) {
  await chrome.storage.local.set(patch);
}

// ── Auth — local token (no credentials needed) ────────────────────────────────

async function fetchLocalToken() {
  const r1 = await fetch(`${TD_HOST}/local-token`);
  if (!r1.ok) throw new Error(`local-token: HTTP ${r1.status}`);
  const { token: localToken } = await r1.json();

  const r2 = await fetch(`${TD_HOST}/auth/local`, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify({ token: localToken }),
  });
  if (!r2.ok) throw new Error(`auth/local: HTTP ${r2.status}`);
  const { token: jwt, expires_in_h } = await r2.json();
  return { token: jwt, expiresIn: expires_in_h || 1 };
}

async function getToken() {
  const s   = await getSettings();
  const now = Date.now();

  if (s.token && s.tokenExpiry > now + TOKEN_MARGIN_MS) {
    return s.token;
  }

  try {
    const { token, expiresIn } = await fetchLocalToken();
    const expiry = now + expiresIn * 3_600_000;
    await saveSettings({ token, tokenExpiry: expiry });
    return token;
  } catch (e) {
    console.warn("[TurboDL] Auth failed:", e.message);
    return null;
  }
}

// ── API calls ─────────────────────────────────────────────────────────────────

async function apiSendUrl(url, dest) {
  const s     = await getSettings();
  const token = await getToken();
  if (!token) return { ok: false, error: "TurboDownloader not reachable" };

  try {
    const r = await fetch(`${TD_HOST}/downloads/add`, {
      method:  "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
      body:    JSON.stringify({ url, dest: dest || s.dest || null }),
    });
    if (!r.ok) return { ok: false, error: `HTTP ${r.status}` };
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

async function apiGetStatus() {
  const token = await getToken();
  if (!token) return null;
  try {
    const r = await fetch(`${TD_HOST}/status`, {
      headers: { "Authorization": `Bearer ${token}` },
    });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}

// ── Launch TurboDownloader via custom protocol ────────────────────────────────

function launchViaProtocol(urls) {
  const params = urls.map(u => `url=${encodeURIComponent(u)}`).join("&");
  const link   = `turbodownloader://send?${params}`;
  chrome.tabs.create({ url: link, active: false }, tab => {
    setTimeout(() => { chrome.tabs.remove(tab.id).catch(() => {}); }, 1000);
  });
  showNotification("TurboDownloader is starting… your download will begin shortly.", "success");
}

async function sendInteractive(urls) {
  const s     = await getSettings();
  const token = await getToken();

  if (token) {
    const combined = urls.join("\n");
    try {
      const r = await fetch(`${TD_HOST}/downloads/add_interactive`, {
        method:  "POST",
        headers: { "Content-Type": "application/json", "Authorization": `Bearer ${token}` },
        body:    JSON.stringify({ url: combined, dest: s.dest || null }),
      });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      showNotification(
        urls.length === 1 ? "Sent to TurboDownloader ✓" : `${urls.length} URLs sent to TurboDownloader ✓`,
        "success"
      );
      return;
    } catch (e) {
      console.log("[TurboDL] HTTP failed, trying protocol:", e.message);
    }
  }

  launchViaProtocol(urls);
}

// ── Notifications ─────────────────────────────────────────────────────────────

function showNotification(message, type = "info") {
  chrome.action.setBadgeText({ text: type === "error" ? "✗" : "✓" });
  chrome.action.setBadgeBackgroundColor({
    color: type === "error" ? "#cc4444" : "#2e6b3e"
  });
  setTimeout(() => chrome.action.setBadgeText({ text: "" }), 3000);
}

// ── Context menu ──────────────────────────────────────────────────────────────

function setupContextMenu() {
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id:       "turbo-send",
      title:    "Send to TurboDownloader",
      contexts: ["link"],
    });
    chrome.contextMenus.create({
      id:       "turbo-send-all",
      title:    "Send all links on this page",
      contexts: ["page"],
    });
  });
}

chrome.runtime.onInstalled.addListener(setupContextMenu);
chrome.runtime.onStartup.addListener(setupContextMenu);

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "turbo-send" && info.linkUrl) {
    await sendInteractive([info.linkUrl]);
  } else if (info.menuItemId === "turbo-send-all" && tab?.id) {
    const results = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func:   () => Array.from(document.querySelectorAll("a[href]")).map(a => a.href),
    });
    const urls = results?.[0]?.result || [];
    if (urls.length) await sendInteractive(urls);
  }
});

// ── Download interception ─────────────────────────────────────────────────────

chrome.downloads.onCreated.addListener(async (item) => {
  const s = await getSettings();
  if (!s.intercept) return;

  const ext = item.filename?.split(".").pop()?.toLowerCase();
  if (!ext || !s.extensions.includes(`.${ext}`)) return;

  chrome.downloads.cancel(item.id);
  await sendInteractive([item.url]);
});

// ── Badge: count links on active tab ─────────────────────────────────────────

const tabLinks = new Map();

chrome.tabs.onActivated.addListener(({ tabId }) => {
  const count = tabLinks.get(tabId) || 0;
  chrome.action.setBadgeText({ text: count > 0 ? String(count) : "", tabId });
  chrome.action.setBadgeBackgroundColor({ color: "#1f6aa5", tabId });
});

chrome.tabs.onRemoved.addListener(tabId => tabLinks.delete(tabId));

// ── Messages from content.js / popup / settings ───────────────────────────────

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  (async () => {
    switch (msg.type) {

      case "SEND_URLS":
        await sendInteractive(msg.urls || []);
        sendResponse({ ok: true });
        break;

      case "LINK_COUNT": {
        const tabId = sender.tab?.id;
        if (tabId != null) {
          tabLinks.set(tabId, msg.count);
          chrome.action.setBadgeText({ text: msg.count > 0 ? String(msg.count) : "", tabId });
          chrome.action.setBadgeBackgroundColor({ color: "#1f6aa5", tabId });
        }
        break;
      }

      case "TEST_CONNECTION": {
        try {
          const { token } = await fetchLocalToken();
          sendResponse({ ok: !!token });
        } catch (e) {
          sendResponse({ ok: false, error: e.message });
        }
        break;
      }

      case "GET_STATUS": {
        const data = await apiGetStatus();
        sendResponse({ status: data });
        break;
      }

      case "GET_LINKS": {
        // Content script handles this — just relay
        try {
          const results = await chrome.scripting.executeScript({
            target: { tabId: msg.tabId },
            func:   () => window.__turboDLLinks || [],
          });
          sendResponse({ links: results?.[0]?.result || [] });
        } catch {
          sendResponse({ links: [] });
        }
        break;
      }

      case "RESCAN": {
        try {
          await chrome.scripting.executeScript({
            target: { tabId: msg.tabId },
            files:  ["content.js"],
          });
        } catch {}
        sendResponse({});
        break;
      }

      case "SETTINGS_SAVED":
        await saveSettings({ token: null, tokenExpiry: 0 });
        setupContextMenu();
        break;
    }
  })();
  return true;
});
